# -----------------------------------------------------------------------------
# Flawed config
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Shared configuration
defaults: &defaults
 :moleable:       true  
 :app_name:       TestApp
